Initial code cleanup for rewrite
strongloop/loopback-connector-db2iseries pull request #20
Opened 2017-03-27 17:23 UTC by qpresley

### Description
Starting a re-write based on new versions of ibm_db which includes updated connection pooling and improvements in async operation.  This also is based on updates to loopback-connector and loopback-ibmdb to provide more consistency and code standards across the connectors.

- [x ] New tests added or existing tests modified to cover all changes
- [x ] Code conforms with the [style
  guide](http://loopback.io/doc/en/contrib/style-guide.html)

2017-03-27 18:30 UTC, 0candy commented on lib/db2i.js
> +  // selectStmt.merge(' FOR UPDATE');
This line can be removed.

2017-03-27 18:30 UTC, 0candy commented on lib/migration.js
> +//   };
Do we need all the commented out methods in this file or can they be removed?

2017-03-27 18:30 UTC, 0candy commented on test/init.js
> +  // schema: process.env.DB2I_SCHEMA || 'STRONGLOOP',
This line can be removed.

2017-03-27 20:14 UTC, qpresley commented on lib/migration.js
> +//   };
Kind of hard to tell now that I look at it in more detail.  I was expecting autoupdate among other functions to be common and to be in loopback-ibmdb but they aren't.  I'm going to uncomment all these.  I don't think there are migration tests for this connector yet so it should be fine to ship with this but if I can get it working quickly I'll likely push changes to this as well as IBMDB and add the migration tests.

2017-03-27 20:24 UTC, qpresley commented on lib/migration.js
> +//   };
Had a quick look.  I'm going to state that migration is not supported at this time for this connector as it is going to require writing these functions from scratch as the system catalogs are different than those from the other IBM databases.  We'll have to do a minor update to add migration/discovery later.

2017-04-12 18:48 UTC, b-admike requested changes

2017-04-12 18:48 UTC, b-admike commented on lib/transaction.js
> + * @param {DB2iSeries} DB2 iSeries connector class
JSdoc for `db2i` parameter here

2017-04-12 18:48 UTC, b-admike commented on lib/migration.js
> +  // DB2iSeries.prototype.isActual = function(models, cb) {
remove if dead code, otherwise you can explain why it is commented out

2017-04-12 18:48 UTC, b-admike commented on lib/migration.js
> +        cb(err, indexes);
`return cb(err,indexes);`

2017-04-12 18:48 UTC, b-admike commented on lib/migration.js
> +        cb(err, fields);
`return cb(err, fields);`

2017-04-12 18:48 UTC, b-admike commented on lib/migration.js
> +              'ORDINAL_POSITION AS COLNO,' +
need space after comma? (following the syntax from previous line)

2017-04-12 18:48 UTC, b-admike commented on lib/migration.js
> +  // DB2iSeries.prototype.searchForPropertyInActual =
remove if dead code, otherwise comment as a block and specify why

2017-04-12 18:48 UTC, b-admike commented on lib/discovery.js
> +* @param {Object} db2i
what does the `db2i` object represent here?

2017-04-12 18:48 UTC, b-admike commented on lib/db2i.js
> +          callback(null, data);
`return callback(null, data);`

2017-04-12 18:48 UTC, b-admike commented on lib/db2i.js
> +            self.rollback(conn, function(err) {});
handle `err` here

2017-04-12 18:48 UTC, b-admike commented on lib/db2i.js
> +            conn.close(function(err) {});
handle `err` here

2017-04-12 18:48 UTC, b-admike commented on lib/db2i.js
> +      callback(null, data);
`return callback(null, data);`

2017-04-12 18:48 UTC, b-admike commented on lib/db2i.js
> +      debug('DB2iSeries.prototype.destroyAll stmt: %j data: %j', selectStmt,
I would suggest that you have this debug statement after handling `err`

2017-04-12 18:48 UTC, b-admike commented on lib/db2i.js
> +          callback(null, {count: retVal});
`return callback(null, {count: retVal});`

2017-04-12 18:48 UTC, b-admike commented on lib/db2i.js
> +            self.rollback(conn, function(err) {});
do we care about the `err` returned here? if so, we should handle it

2017-04-12 18:48 UTC, b-admike commented on lib/db2i.js
> +      callback(null, {count: retVal});
`return callback(null, {count: retVal});`

2017-04-12 18:53 UTC, qpresley commented on lib/db2i.js
> +            self.rollback(conn, function(err) {});
No, it isn't really relevant as we can't really do anything about it.

2017-04-12 19:15 UTC, qpresley commented on lib/db2i.js
> +            self.rollback(conn, function(err) {});
I don't like the code order here though and am changing to have the conn.close inside the rollback callback.

2017-04-12 19:16 UTC, qpresley commented on lib/db2i.js
> +      debug('DB2iSeries.prototype.destroyAll stmt: %j data: %j', selectStmt,
The selectData happens to contain the Error array from the statement executed so having this hear gives me the benefit of being able to dump the error content in the debug statement.

2017-04-12 19:42 UTC, b-admike commented on lib/db2i.js
> +      debug('DB2iSeries.prototype.destroyAll stmt: %j data: %j', selectStmt,
k

2017-04-12 20:33 UTC, merged